### ISSUE TITLE
Hey Yangshun

### ISSUE THREAD

**Issue by divyanshu-rawat** [yangshun/facebook-open-source-mentorship-amy-lam#8]
I have applied for FB open-source Mentorship program but didn't hear anything from the facebook till so fat.
It's been 1 month since I applied.
Best
Divyanshu

**Comment by yangshun** [comment]
Duplicate of https://github.com/facebookmicrosites/fbmentorship/issues/54

**Comment by divyanshu-rawat** [comment]
@yangshun can you let me know when I will be receiving notification from Facebook regarding open source program.

**Comment by yangshun** [comment]
Sorry I'm not a program coordinator, I have no insights about that

**Comment by divyanshu-rawat** [comment]
No problem, Thanks a lot.
